(define (square x) 
  (* x x))

(define (sum-of-squares a b) 
  (+ (square a) (square b)))

(define (square-of-two-larger a b c)
  (cond ((and (>= a b) (>= b c)) (sum-of-squares a b))
	((and (>= a c) (>= c b)) (sum-of-squares a c))
	((and (>= b a) (>= a c)) (sum-of-squares b a))
	((and (>= b c) (>= c a)) (sum-of-squares b c))
	((and (>= c a) (>= a b)) (sum-of-squares c a))
	((and (>= c b) (>= b a)) (sum-of-squares c b))))

(square-of-two-larger 2 3 4)
(square-of-two-larger 2 4 3)
(square-of-two-larger 3 2 4)
(square-of-two-larger 3 4 2)
(square-of-two-larger 4 2 3)
(square-of-two-larger 4 3 2)
(square-of-two-larger 3 3 3)
(square-of-two-larger 2 3 3)
(square-of-two-larger 3 2 3)
(square-of-two-larger 3 3 2)