(define (pascal-triangle row column)
  (cond ((= row 1) 1)
	((= column 1) 1)
	((= column row) 1)
	(else (+ (pascal-triangle (- row 1) (- column 1)) (pascal-triangle (- row 1) column)))))

(pascal-triangle 1 1)
(pascal-triangle 2 1)
(pascal-triangle 2 2)
(pascal-triangle 3 1)
(pascal-triangle 3 2)
(pascal-triangle 3 3)
(pascal-triangle 4 1)
(pascal-triangle 4 2)
(pascal-triangle 4 3)
(pascal-triangle 4 4)
(pascal-triangle 5 1)
(pascal-triangle 5 2)
(pascal-triangle 5 3)
(pascal-triangle 5 4)
(pascal-triangle 5 5)

